name: "workflow"
version: "0.2.5"
repository: github.com/weeros/trivy-plugin-workflow
maintainer: weeros
output: false
summary: Scan filesystem,image,sbom resources
description: |-
  A Trivy plugin that workflow scans.
  Usage: trivy workflow TYPE
platforms:
  - selector: # optional
      os: darwin
      arch: amd64
    uri: ./trivy-workflow # where the execution file is (local file, http, git, etc.)
    bin: ./trivy-workflow # path to the execution file
  - selector: # optional
      os: linux
      arch: amd64
    #uri: ./trivy-workflow
    uri: https://github.com/weeros/trivy-plugin-workflow/releases/download/v0.2.5/trivy-workflow.tar.gz
    bin: ./trivy-workflow
  - selector:
      os: darwin
      arch: arm64
    uri: ./trivy-workflow
    bin: ./trivy-workflow
