name: Release

permissions:
  contents: write
  
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress
        run: tar -zcvf trivy-lp-workflow.tar.gz trivy-lp-workflow LICENSE
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            trivy-lp-workflow.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}